a = str('test')
b= int(5)
c = float(3.14)
d = bool(True)
e = bool(False)
f =[1,2,3,4,5]
g ={1,2,3,4,5}
i = range(1,10)
j = tuple([1,2,3,4,5])
k = list([1,2,3,4,5])
l = dict({1:2,3:4,5:6})
m = object()

print(a)
print(type(a) is str)
print(b)
print(type(b) is int)
print(c)
print(type(c) is float)
print(d)
print(type(d) is bool)
print(e)
print(type(e) is bool)
print(f)
print(type(f) is list)
print(g)
print(type(g) is tuple)
print(i)
print(type(i) is range)
print(j)
print(type(j) is tuple)
print(k)
print(type(k) is list)
print(l)
print(type(l) is dict)
print(m)
print(type(l) is object)